# Site settings
title: Coding Paws - Entwicklertagebuch
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Aus dem täglichen Entwickler-Leben.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://coding-paws.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  rfoerthe

# Build settings
markdown: kramdown
